<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>false</InvariantGlobalization>
    <RootNamespace>GarageGroup.Internal.ProductionCalendar</RootNamespace>
    <AssemblyName>GarageGroup.Internal.ProductionCalendar.Service.Storage.Contract</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../ProductionCalendar/Contract/Contract.csproj" />
    <PackageReference Include="PrimeFuncPack.Core.Failure" Version="2.2.0" />
    <PackageReference Include="PrimeFuncPack.Core.Result" Version="2.0.2" />
  </ItemGroup>

</Project>
